import Logo from '../img/main.jpg'

const intro = [
    {
        logo: Logo,
        delay: "300",
        heading: "Upstart Pioneer",
        price: "1,50,000",
        detail_para: `The "Upstart Pioneer" competition is a must-attend opportunity for any entrepreneur looking to kickstart their startup's growth. This competition offers a comprehensive package that includes not only capital and a cash prize but also valuable advice and mentorship from a panel of experts, as well as extensive networking opportunities with other industry professionals. The event is designed to provide participants with the tools and resources they need to successfully establish a large company, including mentorship and guidance from a network of experienced venture capitalists, angel investors, incubation hubs, and entrepreneurs. After which, there will be a closed-door pitching in front of reputed VCs. So if you're looking to take your startup to the next level, don't miss out on the chance to be a part of the "Upstart Pioneer" event!`
    },
    {
        logo: Logo,
        delay: "600",
        heading: "Pitch Premier",
        price: "1,00,000",
        detail_para: `"Pitch Premier" is an exciting event designed specifically for university students enrolled in undergraduate or graduate programs. The event provides a platform for participants to showcase their entrepreneurial skills and turn their innovative ideas into successful businesses. With a focus on protecting intellectual property and patent rights, "Pitch Premier" encourages participants to not only present their ideas but also develop a plan for future research and development. This event is a unique opportunity for students to demonstrate their all-around talents and bring their entrepreneurial vision to life. If you're a student with a passion for entrepreneurship, "Pitch Premier" is the perfect place to launch your next big idea.`
    }, {
        logo: Logo,
        delay: "900",
        heading: "Analytics Attax",
        price: "75,000",
        detail_para: `In order to find relevant information, support inferences, and help decision-making, data analytics is the process of analysing, cleaning, manipulating, and modelling data. Due to its vast applications, it is used in different business, science, and social science domains. Participants in this competition will receive access to a database of a corporation that contains various details about it. The systematic computational analysis of data or statistics is known as analytics. It is employed for the identification, explanation, and dissemination of significant data patterns. It also involves using data patterns to make smart decisions. Data analytics contributes to more scientific decision-making and more efficient business operations in the modern business world.`
    }, { logo: Logo, delay: "1200", heading: "Marketing Mavericks", price: "75,000", detail_para: `It is a company's strategy for attracting potential customers and converting them into users of their goods or services. It includes their value propositions, critical brand messaging, information on the demographics of their target market, and other important aspects of the company's brand. A marketing plan, a document with all the information mentioned, contains the marketing strategy.This competition will have MCQs in the first round, followed by an abstract and then a ppt presentation in further rounds.` }, { logo: Logo, delay: "1500", heading: "Strategy Sprint", price: "75,000", detail_para: `Students will get the opportunity to strengthen their skills in case analysis, network with consultants in a professional atmosphere, and engage in brainstorming the best ideas alongside some of the brightest minds from across the country. So, put on your consultant hats and get ready to address a critical consulting case problem your client is now dealing with.` }, { logo: Logo, delay: "1800", heading: "Product Showdown", price: "75,000", detail_para: `"Good management is the art of making problems so interesting and their solutions so constructive that everyone wants to get to work and deal with them." - Paul Hawken. Product Showdown is a Business Event in Techkriti '23. It is an event where you can demonstrate and groom the managing skills that you acquire during the course of life. It would test participants on their ability to connect and apply their knowledge in general management, finance, marketing, operations, etc. and come up with the best possible solution for the problem statement.` }, { logo: Logo, delay: "2100", heading: "Trading", price: "50,000", detail_para: `Stock marketing describes the different exchanges where shares of various publicly traded and international corporations are bought and sold. It offers a virtual trading platform that is available from all around the world.TECHKRITI' 23 presents the finest platform to trade risk-free equities in the Virtual Stock Market.` }]

export default intro